### ISSUE TITLE
Fun-task in react/redux 

### ISSUE THREAD

**Issue by bachstatter** [rpominov/fun-task#30]
Hey! 

Fun-task seems really good, can't wait to play around with it.  Do you have any experience using it in a react & redux application or seen other people do it? 

Thanks for a cool library

**Comment by rpominov** [comment]
Hi, good question!

I've actually started this library because I wanted to use something like this in react/redux projects. And I had some ideas back then. But unfortunately I didn't have an opportunity to use it in a react project so far, and I ended up forgetting those ideas. So I can't point to something in particular, but for a start fun-task can be used instead of promises in a similar fashion.

Also I had this idea I wanted to try with server-side rendering: https://github.com/rpominov/fun-task/issues/1#issuecomment-235662732 . But I haven't tried it so can't really tell if it's a good idea.

I'll close this because these types of issues can't be resolved. But feel free to keep the discussion going of course. Also maybe someone else has something to add.
